version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: file_repository
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
